# Generated by Django 3.0.6 on 2020-10-20 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avantage',
            options={'verbose_name': 'Avantage', 'verbose_name_plural': 'Avantages'},
        ),
        migrations.AlterModelOptions(
            name='chiffre',
            options={'verbose_name': 'Chiffre', 'verbose_name_plural': 'Chiffres'},
        ),
        migrations.AlterModelOptions(
            name='taffich',
            options={'verbose_name': 'Taffich', 'verbose_name_plural': 'Taffichs'},
        ),
    ]
