# Generated by Django 3.0.6 on 2020-10-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0002_auto_20201020_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avantage',
            name='nombre',
        ),
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
