# Generated by Django 3.0.6 on 2020-10-20 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201020_1507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
