# Generated by Django 3.0.6 on 2020-10-23 17:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=tinymce.models.HTMLField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='article',
            name='resume',
            field=tinymce.models.HTMLField(verbose_name='resume'),
        ),
    ]
