# Generated by Django 3.0.6 on 2020-10-23 12:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_review_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='resume',
            field=tinymce.models.HTMLField(default='', verbose_name='shop/resume'),
            preserve_default=False,
        ),
    ]
