# Generated by Django 3.0.6 on 2020-10-24 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='auteur',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='useprod', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
